In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-10-24 19:32:19.640168: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
sentences = [
    'Aliens stole my homework yesterday',
    'Giraffes are terrible at limbo',
    'My pillow speaks French',
    'Zombies hate morning yoga',
    'Monkeys won the lottery',
    'Cats secretly rule everything',
    'Bananas fear the blender'
]

In [3]:
# Define vocabulary size
voc_size = 10000

In [4]:
# Integer encoding of words using the one_hot function
one_hot_repr = [one_hot(words, voc_size) for words in sentences]

one_hot_repr
    

[[6310, 2762, 1802, 310, 6359],
 [5144, 1244, 9153, 165, 9510],
 [1802, 4251, 8929, 9922],
 [4927, 7317, 8909, 4282],
 [2369, 3753, 1048, 4845],
 [684, 4675, 6877, 9811],
 [6652, 8547, 1048, 4356]]

In [10]:
# Word embeddings
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [6]:
# Ensure sentence lengths are equal
max_sentence_length = 8

# 'pre' adds zeros at the front of the sentence vector
# 'post' adds at the end
embedded_docs = pad_sequences(one_hot_repr, padding='post', maxlen=max_sentence_length)

print(embedded_docs)

[[6310 2762 1802  310 6359    0    0    0]
 [5144 1244 9153  165 9510    0    0    0]
 [1802 4251 8929 9922    0    0    0    0]
 [4927 7317 8909 4282    0    0    0    0]
 [2369 3753 1048 4845    0    0    0    0]
 [ 684 4675 6877 9811    0    0    0    0]
 [6652 8547 1048 4356    0    0    0    0]]


In [7]:
# Feature representation
dimensions = 10

In [17]:
model = Sequential()
model.add(Input(shape=(max_sentence_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dimensions)) # OR model.add(Embedding(voc_size, dimensions))

model.compile('adam', 'mse') # OR model.compile(optimizer='adam', loss='mse')


In [18]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step


array([[[ 1.60959028e-02,  3.48801352e-02, -3.17474976e-02,
          3.69214155e-02, -1.10222213e-02,  3.75268608e-03,
          3.06533240e-02,  2.51022093e-02, -9.78858396e-03,
         -2.34676842e-02],
        [ 1.23915561e-02, -2.35045087e-02,  2.94922478e-02,
         -4.20866162e-03,  2.85221674e-02,  6.97679445e-03,
          8.70901346e-03,  2.81994455e-02,  4.91221882e-02,
          2.93339416e-03],
        [ 3.64967249e-02, -1.04799382e-02, -2.63861902e-02,
         -6.43979385e-03, -2.26754900e-02,  8.29994678e-04,
          1.80827640e-02, -4.45511118e-02, -4.77311499e-02,
         -7.39179924e-03],
        [ 2.35509314e-02,  4.19173576e-02,  2.49320529e-02,
         -7.74247572e-03, -2.81782746e-02, -3.99086252e-02,
          4.01606597e-02,  2.40764134e-02, -3.89589295e-02,
          2.19110288e-02],
        [ 3.16828974e-02,  1.00348108e-02, -1.13738291e-02,
         -3.82328629e-02, -4.87306230e-02,  3.66144888e-02,
          6.20659441e-03, -2.68979203e-02,  1.684460

In [20]:
embedded_docs[0]

array([6310, 2762, 1802,  310, 6359,    0,    0,    0], dtype=int32)